In [1]:
import numpy as np
from numpy import array

M = array([[1, 3, 0], [0, 1, 1], [0, 0, 2]])
print(M)

[[1 3 0]
 [0 1 1]
 [0 0 2]]


In [5]:
tr_M = np.trace(M)
print(tr_M)

4


In [7]:
diag_M = np.diag(M)
print(diag_M)

[1 1 2]
