In [4]:
import numpy as np
from numpy import array

A = array([[1, 1], [4, -3]])
print(A)
y = array([[5],[0]])
print(y)

[[ 1  1]
 [ 4 -3]]
[[5]
 [0]]


In [5]:
x = np.linalg.solve(A, y)

print(x)

[[2.14285714]
 [2.85714286]]
