In [1]:
from space import *
import numpy as np

# Solution for A1
class CloudRotateScale(space):
    # Constructor
    def __init__(self):
        super().__init__()
        # Matrix
        self.X = np.array([[1, 0, 0], [0, 1, 0], [0, 0 ,1], [-1, 0 ,0]])
        # Cloud points
        self.cloud = point_cloud(X = self.X)

        # Starting angle
        self.angle = 0.0
        #target angle
        self.target = np.pi / 2
        # Speed of animation
        self.speed = 0.05

        # m button starts the rotation
        self.accept("m", self.start)
        
        self.animating = False
        self.taskMgr.add(self.update, "update_rotation")

    # Does the rotation
    def start(self):
        self.angle = 0.0
        self.animating = True
        self.cloud.redraw(self.X)

    def update(self, task):
        # Update the angle
        if not self.animating:
            return Task.cont
        self.angle += self.speed
        if self.angle >= self.target:
            self.angle = self.target
            self.animating = False
        a = self.angle

        # Rotation matrix
        Rz = np.array([[np.cos(a), -np.sin(a), 0], [np.sin(a), np.cos(a), 0], [0, 0, 1]])

        # Rotated matrix
        X_rot = self.X @ Rz.T
        
        # Scaled matrix
        X_final = 2 * X_rot

        self.cloud.redraw(X_final)

        return Task.cont
        
app = CloudRotateScale()
app.run()

Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)


SystemExit: 

/Users/tjgribbin/.pyenv/versions/3.11.8/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3709: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
from space import *
import numpy as np

# Solution for A2
class CenterPoints(space):
    # Constructor
    def __init__(self):
        super().__init__()

        # Original array
        X1 = np.array([[2, 3], [4, 5], [6, 7], [8, 9]])

        # Convert to 3d points
        self.X1 = np.hstack([X1, np.zeros((X1.shape[0], 1))])

        self.cloud = point_cloud(X = self.X1)

        # m ceenters the points
        self.accept("m", self.center_points)

    def center_points(self):
        # Number of points
        n = self.X1.shape[0]

        # Vector of ones
        ones = np.ones((n, 1))

        
        # Centering matrix
        H = np.eye(n) - (1/n) * (ones @ ones.T)

        # Centered matrix
        X1_centered = H @ self.X1

        self.cloud.redraw(X1_centered)

        return Task.cont

app = CenterPoints()
app.run()

In [1]:
from space import *
import numpy as np
# Solution for A3
class InteractiveTransform(space):
    def __init__(self):
        super().__init__()

        # 8 corners of the rectangular prism (rows are points)
        self.P = np.array([
            [3, 1, 2],
            [5, 1, 2],
            [5, 4, 2],
            [3, 4, 2],
            [3, 1, 5],
            [5, 1, 5],
            [5, 4, 5],
            [3, 4, 5],
        ])

        self.cloud = point_cloud(X = self.P)

        self.rot_step = np.pi / 18

        self.scale_up = 1.1

        self.scale_down = 0.9

        self.accept("x", self.rotate_x)
        self.accept("y", self.rotate_y)
        self.accept("z", self.rotate_z)
        self.accept("b", self.scale_bigger)
        self.accept("s", self.scale_smaller)

    def mean(self, X):
        return X.mean(axis = 0)

    # Centering before the other transformations are neccesary because the transformations are defined in terms of the origin
    # If the object is not centered the object will just move instead of changing it's size or rotation
        
    def apply_centered_transform(self, T):
        # Get current positions
        X = self.cloud.pos()
        # Mean position of the object
        c = self.mean(X)     
        # Subtract the mean from each point
        Xc = X - c                        
        # Multipy the mean points by the transformation matrix 
        Xc_new = Xc @ T.T
        # Add the mean back to each point
        X_new = Xc_new + c      
        # Update the points
        self.cloud.redraw(X_new)

    def rotX(self, angle):
        return np.array([
            [1, 0, 0],
            [0, np.cos(angle), -np.sin(angle)],
            [0, np.sin(angle),  np.cos(angle)],
        ])

    def rotY(self, angle):
        return np.array([
            [ np.cos(angle), 0, np.sin(angle)],
            [0, 1, 0],
            [-np.sin(angle), 0, np.cos(angle)],
        ])

    def rotZ(self, angle):
        return np.array([
            [np.cos(angle), -np.sin(angle), 0],
            [np.sin(angle),  np.cos(angle), 0],
            [0, 0, 1],
        ])

    def scale(self, k):
        return np.array([
            [k, 0, 0],
            [0, k, 0],
            [0, 0, k],
        ])

    def rotate_x(self):
        self.apply_centered_transform(self.rotX(self.rot_step))
        return Task.cont

    def rotate_y(self):
        self.apply_centered_transform(self.rotY(self.rot_step))
        return Task.cont

    def rotate_z(self):
        self.apply_centered_transform(self.rotZ(self.rot_step))
        return Task.cont

    def scale_bigger(self):
        self.apply_centered_transform(self.scale(self.scale_up))
        return Task.cont

    def scale_smaller(self):
        self.apply_centered_transform(self.scale(self.scale_down))
        return Task.cont


app = InteractiveTransform()
app.run()

Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)


SystemExit: 

/Users/tjgribbin/.pyenv/versions/3.11.8/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3709: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
from panda3d.core import Filename
from space import space
#A5 Part 1
class load_example(space):
    def __init__(self):
        super().__init__()
        house = self.load_mesh("little_house_mesh.glb")
        house.setScale(2)
        house.setPos(0, 0, 1)
        house.setHpr(0, 90, 0)

app = load_example()
app.run()

Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)


SystemExit: 

/Users/tjgribbin/.pyenv/versions/3.11.8/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3709: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
from space import *
import numpy as np
# A5 Part 2
class Airplane(space):
    def __init__(self):
        super().__init__()

        # Load the airplane mesh
        self.plane = self.load_mesh("airplane.glb")
        self.plane.setScale(2)
        self.plane.setPos(0, 5, 0)

        # Start and end points
        self.p1 = np.array([0,  5, 0])
        self.p2 = np.array([1, -6, 5])
        self.plane.setHpr(0, 90, 0)

        # Animation state
        self.t = 0.0
        self.dt = 0.01
        self.flying = False

        # Space bar starts animation
        self.accept("space", self.start)

        # Task loop
        self.taskMgr.add(self.update, "fly")

    def start(self):
        self.t = 0.0
        self.flying = True
        return Task.cont

    def update(self, task):
        if not self.flying:
            return Task.cont

        # p(t) = (1 - t)p1 + t p2
        p = (1 - self.t) * self.p1 + self.t * self.p2

        # Move the airplane
        self.plane.setPos(float(p[0]), float(p[1]), float(p[2]))

        self.t += self.dt

        if self.t >= 1.0:
            self.t = 1.0
            self.flying = False

        return Task.cont


app = Airplane()
app.run()

Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)


SystemExit: 

/Users/tjgribbin/.pyenv/versions/3.11.8/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3709: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [3]:
import numpy as np 
# B6
A1 = np.array([[2, 3],[1, 2]])

A2 = np.array([[1, 2, 3], [0, 1, 4], [2, 1, 0]])

A3 = np.array([[1, 2, 3], [2, 4, 6], [0, 0, 0]])

D = np.array([[1, 2, 1, 0], [0, 1, 4, 1], [0, 0, 1, 3], [0, 0, 0, 1]])

def inverse_if_invertible(M):
    det = np.linalg.det(M)

    if det == 0:
        print("Matrix is not invertible\n")
        return None
    inv = np.linalg.inv(M)
    return inv

print(inverse_if_invertible(A1))
print()
print(inverse_if_invertible(A2))
print()
print(inverse_if_invertible(A3))
print()
print(inverse_if_invertible(D))

[[ 2. -3.]
 [-1.  2.]]

[[-0.66666667  0.5         0.83333333]
 [ 1.33333333 -1.         -0.66666667]
 [-0.33333333  0.5         0.16666667]]

Matrix is not invertible

None

[[  1.  -2.   7. -19.]
 [  0.   1.  -4.  11.]
 [  0.   0.   1.  -3.]
 [  0.   0.   0.   1.]]


In [4]:
import numpy as np

A = np.array([[ 2,  3,  4], [ 0, -1,  5], [ 0,  0,  3]])

B = np.array([[-1,  0,  0], [ 2,  4,  0], [ 1, -3,  2]])

C = np.array([[-2,  0,  0], [ 2,  0,  4],[ 1, -3, -3]])

# Part A
print("det(A) =", np.linalg.det(A))
print("det(B) =", np.linalg.det(B))
print("det(C) =", np.linalg.det(C))
print()

# Part B
print("det(2B) =", np.linalg.det(2 * B))
print()

# Part C
expr_c = 2 * B @ A.T
print("det(2 B A^T) =", np.linalg.det(expr_c))
print()

# Part D
expr_d = A @ B @ C
print("det(ABC) =", np.linalg.det(expr_d))
print()

det(A) = -6.0
det(B) = -7.999999999999998
det(C) = -23.999999999999993

det(2B) = -64.00000000000003

det(2 B A^T) = 384.0

det(ABC) = -1152.0000000000005



In [5]:
import numpy as np

M = np.linalg.inv(A) @ B.T @ C @ A

print("det(M) =", np.linalg.det(M))

det(M) = 192.00000000000188
